---
- hosts: all
  become: true

  vars:
    mysource: "/var/lib/rundeck/ansible/checklist/templates/"
    data:  'date +%F-%H-%M-%S' 

  tasks:

    - name: Baixar Pacote do Zabbix
      yum: 
        name: https://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/zabbix-release-3.2-1.el7.noarch.rpm
        state: present
    
    - name: Instala Zabbix
      yum:
        name: zabbix-agent
        state: installed

    - name: Verifica se arquivo existe de conf Zabbix
      stat: path=/etc/zabbix/zabbix_agentd.conf
      register: conf_agent

    - name: Faz o Backup       
      action: raw mv /etc/zabbix/zabbix_agentd.conf /etc/zabbix/zabbix_agentd.conf-old
      when: conf_agent.stat.exists

    - name: Copiar Template zabbix_agent
      template: 
        src: "{{ mysource }}zabbix_agentd.conf.j2"
        dest: "/etc/zabbix/zabbix_agentd.conf"
        owner: root
        mode: 0644

:
